name: Build

on:
  push:
    branches-ignore: [main]
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: ['14', '16']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci --force --prefer-offline --no-audit

      - name: Build project
        run: npm run build

      - name: Unit tests
        run: npm run test

      - name: Upload artifact
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '16'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build
          retention-days: 1